	SecId
	Ticker
      Ticker
      StandardName
      AlphaName
      SecurityType
      Exchange
      Sector
      Industry
      IndustryCode
      Type
      EquityStyleBox
      CurrentPrice
      DailyPriceDate
      MarketCap
      SharesOutstanding
      SharesOutstandingYear1
      SharesOutstandingYear2
      SharesOutstandingYear3
      SharesOutstandingYear4
      SharesOutstandingYear5
      CurrentReturn
      AverageDailyVolume
      Price52WeekHigh
      Price52WeekLow
      LastStockSplit
      FundOwnership
      InSP500
      State
      CountryId
      DRIP
      DirectInvestment
      Employees
      ReportDate
      Homepage
      LocalPhone
      EconomicMoat
      RawStyle
      RawSize
      EPSEstDownRevCurrentYear
      EPSEstGrowthMean5Year
      EPSEstMeanCurrentYear
      EPSEstMeanNextYear
      EPSEstNumberOfAnalysts
      EPSEstUpRevCurrentYear
      EPSEst30DayAgo
      EPSEst60DayAgo
      EPSEst90DayAgo
      ActualExpectedEPSQ1
      ActualExpectedEPSQ2
      ActualExpectedEPSQ3
      ActualExpectedEPSQ4
      SustainableGrowthRate
      PEGPaybackYears
      RiskRating
      GrowthGradeScore
      ProfitabilityGradeScore
      FinancialHealthGradeScore
      ProspectiveEarningsYield
      ProspectiveRevenueYield
      ProspectiveCashFlowYield
      ProspectiveDividendYield
      ProspectiveBookValueYield
      ForecastedEarningsGrowthRate
      ForecastedRevenueGrowthRate
      ForecastedCashFlowGrowthRate
      ForecastedBookValueGrowthRate
      Forecasted5YearEarningsGrowthRate
      RevenueTTM
      RevenueYear1
      RevenueYear2
      RevenueYear3
      RevenueYear4
      RevenueYear5
      RevenueYear6
      RevenueYear7
      RevenueYear8
      RevenueYear9
      RevenueYear10
      RevenueChgY1ToY2
      RevenueChgY2ToY3
      RevenueChgY3ToY4
      RevenueChgY4ToY5
      NetIncomeTTM
      NetIncomeYear1
      NetIncomeYear2
      NetIncomeYear3
      NetIncomeYear4
      NetIncomeYear5
      NetIncomeChgY1ToY2
      NetIncomeChgY2ToY3
      NetIncomeChgY3ToY4
      NetIncomeChgY4ToY5
      EPSContOpsTTM
      EPSContOpsYear1
      EPSContOpsYear2
      EPSContOpsYear3
      EPSContOpsYear4
      EPSContOpsYear5
      EPSTTM
      EPSYear1
      EPSYear2
      EPSYear3
      EPSYear4
      EPSYear5
      EPSYear6
      EPSYear7
      EPSYear8
      EPSYear9
      EPSYear10
      EPSQuarter1
      EPSQuarter2
      EPSQuarter3
      EPSQuarter4
      EPSQuarter5
      EPSQuarter6
      EPSQuarter7
      EPSQuarter8
      EPSChgQ1ToQ5
      EPSChgQ2ToQ6
      EPSChgQ3ToQ7
      EPSChgQ4ToQ8
      DividendPerShareTTM
      DividendPerShareYear1
      DividendPerShareYear2
      DividendPerShareYear3
      DividendPerShareYear4
      DividendPerShareYear5
      CashYear1
      CashQuarter1
      CurrentAssetsYear1
      NoncurrentAssetsQuarter1
      CurrentLiabilitiesYear1
      InventoryYear1
      LongTermLiabilitiesYear1
      LongtermLiabilitiesQuarter1
      NoncurrentAssetsYear1
      TotalAssetsYear1
      TotalEquityYear1
      TotalLiabilitiesYear1
      CurrentAssetsQuarter1
      CurrentLiabilitiesQuarter1
      TotalAssetsQuarter1
      TotalEquityQuarter1
      TotalLiabilitiesQuarter1
      LongtermDebtQuarter1
      InventoryQuarter1
      CapitalSpendingTTM
      CapitalSpendingYear1
      CashFlowOtherYear1
      CashFlowFromOpsTTM
      CashFlowFromOpsYear1
      CashReturn
      FreeCashFlowTTM
      FreeCashFlowYear1
      FreeCashFlowYear2
      FreeCashFlowYear3
      DeferredTaxesYear1
      DeprecAmortYear1
      AnnualReturnYear1
      AnnualReturnYear2
      AnnualReturnYear3
      AnnualReturnYear4
      AnnualReturnYear5
      AnnualReturnYear6
      AnnualReturnYear7
      AnnualReturnYear8
      AnnualReturnYear9
      AnnualReturnYear10
      TotalReturnYTD
      TotalReturn1Month
      TotalReturn3Month
      TotalReturn1Year
      TotalReturn3Year
      TotalReturn5Year
      TotalReturn10Year
      TotalReturnRankInd1Month
      TotalReturnRankInd3Month
      TotalReturnRankIndYTD
      TotalReturnRankInd1Year
      TotalReturnRankInd3Year
      TotalReturnRankInd5Year
      TotalReturnRankInd10Year
      MonthlyReturnYTD
      MonthlyReturn1Month
      MonthlyReturn3Month
      MonthlyReturn1Year
      MonthlyReturn3Year
      MonthlyReturn5Year
      MonthlyReturn10Year
      Best3MonthReturn
      Worst3MonthReturn
      ROARankIndustryYear1
      ROERankIndustryYear1
      AverageVolume3Month
      AverageVolume1Year
      DailyCompanyProprietaryDataDates 
      Symbol
      PerformanceStartDate
      Price10YearHigh
      Price10YearLow
      CurrentFiscalPeriodDate
      BasicAverageSharesTTM
      AssetTurnoverTTM
      WorkingCapitalQuarter1
      GrowthGradeScoreDate
      EPSEstCurFYDate
      EPSEstNextFYDate
      LTEarningsGrowthEstDate
      Price52WeekHighDate
      Price52WeekLowDate
      MarketCapAsOfDate
      EnterpriseValue
      SectorCode
      StockTypeCode
      EPSEst30DayAgoDate
      EPSEst60DayAgoDate
      EPSEst90DayAgoDate
      SEDOL
      SecurityType2
      IsADR
      BusinessCountryId
      RussellGlobalSector
      RussellGlobalSubSector
      RussellGlobalIndustry
      FloatShares
      IsPrimaryShare
      AddressLine1
      PostalCode
      MSCICountryId
      MSCIRegionId
      MSCISuperRegionId
      RusselCountryId
